version: 1.0.{build}
before_build:
- cmd: nuget restore src\DataTableFormatters.sln -verbosity detailed
build:
  project: src\DataTableFormatters.sln
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: src\DataTableFormatters\**\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: q+O+3OHvLzlzP975Tg8bB3tRCa+m/MJmcMiM/dDCzEvWWHi3h1xhmsfzGX94fkDH
  on:
    branch: master