version: 1.0.{build}
branches:
  except:
  - master
skip_commits:

  # Regex for matching commit message
  message: /Created.*\.(png|jpg|jpeg|bmp|gif)/

  # Commit author's username, name, email or regexp maching one of these.
  author: John
before_build:
- cmd: nuget restore src\DataTableFormatters.sln -verbosity detailed
build:
  project: src\DataTableFormatters.sln
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: src\DataTableFormatters\**\*.nupkg
